In [1]:
import torch
import torch.nn as nn

In [14]:
a = torch.randn(3, 2, 10,10)
conv2 = nn.Conv2d(2, 10, (3,3), padding=1)
b = conv2(a)
a.shape, b.shape

(torch.Size([3, 2, 10, 10]), torch.Size([3, 10, 10, 10]))

In [18]:
a = torch.randn(3, 2)
a

tensor([[-2.5798, -0.4835],
        [-0.7570,  0.1260],
        [-0.9824, -1.9866]])

In [20]:
a.permute(1,0)

tensor([[-2.5798, -0.7570, -0.9824],
        [-0.4835,  0.1260, -1.9866]])

In [21]:
a.reshape(2,3)

tensor([[-2.5798, -0.4835, -0.7570],
        [ 0.1260, -0.9824, -1.9866]])

In [22]:
import torch
import torch.nn.functional as F

# 입력 텐서 (B, T, D)
B, T, D = 2, 5, 4
X = torch.randn(B, T, D)

# 가중치 행렬
W_q = torch.randn(D, D)
W_k = torch.randn(D, D)
W_v = torch.randn(D, D)

# Q, K, V 행렬 계산
Q = X @ W_q  # (B, T, D)
K = X @ W_k  # (B, T, D)
V = X @ W_v  # (B, T, D)

# Attention Score 계산
Score = Q @ K.transpose(-2, -1) / torch.sqrt(torch.tensor(D, dtype=torch.float32))  # (B, T, T)

# Softmax를 통한 정규화
Attention_Weight = F.softmax(Score, dim=-1)  # (B, T, T)

# 최종 출력 계산
Output = Attention_Weight @ V  # (B, T, D)

print("Input Shape:", X.shape)
print("Output Shape:", Output.shape)

Input Shape: torch.Size([2, 5, 4])
Output Shape: torch.Size([2, 5, 4])


In [2]:
input = torch.randn(1,64,257)
conv1 = nn.Conv1d(8, 8, 5, padding=2)

In [3]:
conv1.weight.shape

torch.Size([8, 8, 5])

In [5]:
conv1(input[:,:8,:]).shape

torch.Size([1, 8, 257])